/* build-handoff — one folder a development team can be handed.
 *
 * The owner, 20 Sep 2026: "मेरे repos को भी अच्छे से organize कर दो, जिससे कि मैं dev team को
 * उनको दूँ, तो वो उससे properly design system extract कर पाएँ, fully, with design rules के साथ,
 * and सारी screens उनको मिल जाएँ।"
 *
 * So this emits `handoff/` with four things and nothing else:
 *   design-system/   the system, whole: components, contracts, prompts, tokens, guidelines, barrel
 *   screens/         every screen module and the one fixture they all read
 *   bundles/         two single files, for dropping into a spike without a build step
 *   README.md        what each of those is, and the rules that travel with them
 *
 * It COPIES rather than symlinks, and it is regenerated rather than edited: `handoff/` is a build
 * output. The repository stays the source of truth, which is the same reason `_ds_bundle.js` is
 * generated rather than hand-kept.
 */
import { cp, mkdir, rm, writeFile, readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'handoff');

const walk = async (dir, filter, acc = []) => {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.')) continue; // .DS_Store and friends are not content
    const p = join(dir, e.name);
    if (e.isDirectory()) await walk(p, filter, acc);
    else if (filter(p)) acc.push(p);
  }
  return acc;
};

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

/* 1 · THE SYSTEM, WHOLE. Every component with its contract and its prompt, the tokens, the
   guidelines, the spec pages, and the generated barrel that is the only public entry. */
await cp(join(ROOT, 'design-system'), join(OUT, 'design-system'), { recursive: true });
await rm(join(OUT, 'design-system', 'ui_kits'), { recursive: true, force: true });

/* 2 · THE SCREENS. The modules, the fixture, and the pages that render them — so "give me the code
   for that screen" is answered by a path rather than by a conversation. */
await cp(join(ROOT, 'screens'), join(OUT, 'screens'), { recursive: true });

/* 3 · TWO SINGLE FILES, for a spike that does not want a build step. The system's is the bundle the
   preview pages already load, which is the honest one to hand over: it is what every screenshot in
   this repository was taken against. The screens' is a concatenation in load order, and load order
   is not incidental — every screen module compiles into ONE scope and several read the ones before. */
await mkdir(join(OUT, 'bundles'), { recursive: true });
await cp(join(ROOT, 'design-system', '_ds_bundle.js'), join(OUT, 'bundles', 'sentinel-design-system.js'));

const ORDER = ['screens/screen-kit.jsx', 'screens/data/book.jsx', 'screens/journey-b/thread.jsx', 'screens/journey-b/home.jsx'];
const all = (await walk(join(ROOT, 'screens'), (p) => p.endsWith('.jsx'))).map((p) => relative(ROOT, p));
const ordered = [...ORDER.filter((f) => all.includes(f)), ...all.filter((f) => !ORDER.includes(f)).sort()];
const parts = [];
parts.push(`/* Sentinel — every screen module, concatenated in load order.\n   Generated by tools/build-handoff.mjs. Do not edit: edit the files under screens/.\n\n   LOAD ORDER IS NOT INCIDENTAL. These compile into ONE scope and several read the ones before them:\n   screen-kit publishes the four promoted turn components, book.jsx is the single fixture every screen\n   reads, and thread.jsx carries the attachment state the journeys share. */\n`);
for (const f of ordered) {
  parts.push(`\n/* ${'='.repeat(92)}\n   ${f}\n   ${'='.repeat(92)} */\n`);
  parts.push(await readFile(join(ROOT, f), 'utf8'));
}
await writeFile(join(OUT, 'bundles', 'sentinel-screens.jsx'), parts.join(''));

/* 4 · THE RULES THAT TRAVEL WITH THEM. Copied, not summarised: a rule paraphrased into a handoff is
   a rule with two versions. */
await mkdir(join(OUT, 'rules'), { recursive: true });
for (const f of ['docs/HANDOVER.md', 'docs/DNA.md', 'docs/FEEL.md', 'docs/DEMO-SCRIPT.md', 'CONTRIBUTING.md', 'design-system/readme.md', 'design-system/guidelines/contradictions.md']) {
  if (existsSync(join(ROOT, f))) await cp(join(ROOT, f), join(OUT, 'rules', f.split('/').pop()));
}

const count = async (dir, ext) => (await walk(join(OUT, dir), (p) => p.endsWith(ext))).length;
const readme = `# Sentinel — handoff

Generated by \`npm run build:handoff\`. **Do not edit anything in here** — it is a build output, and
the repository it came from is the source of truth.

## What is in it

| Folder | What it is |
|---|---|
| \`design-system/\` | The system, whole. ${await count('design-system/components', '.jsx')} components, each with a \`.d.ts\` contract and a \`.prompt.md\`; \`tokens/\` is every value the system allows; \`pages/\` is a rendered specification for the components that have one; \`guidelines/\` is the foundations, including the system's own list of known inconsistencies |
| \`screens/\` | Every screen, every journey, and \`data/book.jsx\` — the single fixture all of them read |
| \`bundles/\` | Two single files for a spike with no build step |
| \`rules/\` | The rules that travel with the code, copied rather than summarised |

## Start here, in this order

1. **\`rules/HANDOVER.md\`** — install, import, the four rules, and what gets a pull request sent back.
2. **\`rules/readme.md\`** — the system's own specification. Most surprising choices are deliberate and
   explained there; read the relevant section before changing a component.
3. **\`design-system/index.js\`** — the generated barrel and the **only** public entry. Import from it,
   never from a component file: the paths under \`components/\` are an implementation detail.
4. **\`rules/DEMO-SCRIPT.md\`** — every sentence that reaches every screen, so you can drive the
   product before you build it.

## The four rules, in one line each

1. **Colour never encodes identity.** Rank is length, identity is the label. One hue.
2. **Bad news is text on the peach bubble, never a fill.** There is no red panel in this product.
3. **The composer is on every screen.** One documented exception: the confirm sheet, which is
   commit-or-dismiss with no third path — and \`ConfirmSheet\` holds that exception in its type.
4. **Indian grouping, and every figure says where it came from.** \`₹1,85,000\`, not \`₹185,000\`.

## Getting a screen

Every screen is a \`.jsx\` module under \`screens/<journey>/\` plus an \`.html\` page that renders its
states. The module is the code; the page is the specification of what the code must look like in each
state. \`screens/prototype.html\` is all of them, wired together, driven by one router.

## What this is not

It is not an application. There is no router, no data layer and no authentication — \`book.jsx\` is a
fixture, labelled as one on every screen that reads it. What you are getting is the product's design,
made executable, so that what you build can be checked against it rather than described to you.
`;
await writeFile(join(OUT, 'README.md'), readme);

/* AND THE TWO FILES THE OWNER ASKED FOR BY NAME, committed rather than generated-and-gitignored:
   "design system का code file अलग से, screen का code file अलग से". `handoff/` is a build output and
   is not in git; these two are, so a link to the repository is enough to hand them over. */
await mkdir(join(ROOT, 'dist'), { recursive: true });
await cp(join(OUT, 'bundles', 'sentinel-design-system.js'), join(ROOT, 'dist', 'sentinel-design-system.js'));
await cp(join(OUT, 'bundles', 'sentinel-screens.jsx'), join(ROOT, 'dist', 'sentinel-screens.jsx'));

/* THE COPY THAT OPENS TRAVELS WITH THE CODE (20 Sep 2026).
   A handoff of source alone asks the receiving team to install a toolchain before they can see what
   they are being asked to build. `site/` is precompiled and self-contained — 131 pages that open
   from a double-click — so it goes in the folder the team is actually sent. It must already be
   built: this copies, it does not generate, and it says so rather than silently shipping a stale one. */
if (!existsSync(join(ROOT, 'site', 'index.html'))) {
  console.error('site/ is not built — run `npm run build:artifact` first, then this again');
  process.exit(1);
}
await cp(join(ROOT, 'site'), join(OUT, 'site'), { recursive: true });

await writeFile(join(OUT, 'START-HERE.md'), `# Sentinel — start here

Two doors, and they are for different people.

**To look at it:** open \`site/index.html\`. Double-click it. No install and no server — every screen,
every journey and all 94 component specifications are in there, already built. React and the fonts
come from a CDN, so stay online.

**To build it:** read \`README.md\` in this folder, then \`rules/HANDOVER.md\`. The code is under
\`design-system/\` and \`screens/\`; \`bundles/\` has the whole system as one file and every screen as
one file, for a spike with no build step.

Everything here is generated from one repository, which is the source of truth. Do not edit this
folder expecting the changes to survive.
`);

/* One archive, because "download karke team ko bhej dunga" is the actual use. */
const { execFileSync } = await import('node:child_process');
const zip = join(ROOT, 'sentinel-handoff.zip');
await rm(zip, { force: true });
execFileSync('zip', ['-rq', zip, 'handoff', '-x', '*.DS_Store'], { cwd: ROOT });

const jsx = await count('design-system/components', '.jsx');
const dts = await count('design-system/components', '.d.ts');
const pages = await count('design-system/pages', '.html');
const screens = await count('screens', '.jsx');
const { statSync } = await import('node:fs');
console.log(`handoff/: ${jsx} components (${dts} contracts), ${pages} spec pages, ${screens} screen modules, 2 bundles, 131-page site/`);
console.log(`sentinel-handoff.zip: ${(statSync(zip).size / 1048576).toFixed(1)} MB — the one file to send`);
