/* Generates design-system/index.js and index.d.ts — the public entry the adherence config already
   points consumers at ("Import design-system components from 'index.js', not component internals")
   and the one file its overrides exempt from that rule.

   Derived from disk, never from a hand-kept list, for the same reason scripts/build-index.js is:
   a barrel built from a list can claim a component that isn't there. A name is exported because
   the file exports it. Duplicate names abort the build rather than silently shadowing. */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DS = join(dirname(fileURLToPath(import.meta.url)), '..', 'design-system');
/* `brand` added 21 Sep 2026 — the mascot, the dot field and the splash. This list is the gate: a group
   missing here is missing from the barrel, therefore from the bundle, therefore from every page,
   which fail with "Element type is invalid… got: undefined" rather than naming the cause. */
const DIRS = ['brand', 'text', 'icons', 'shell', 'actions', 'forms', 'lists', 'cards', 'chat', 'composer', 'data'];
const NAMED = /^export\s+(?:async\s+)?(?:function|const|class)\s+([A-Za-z_$][\w$]*)/gm;
const TYPES = /^export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)/gm;

const scan = (src, re) => [...src.matchAll(re)].map((m) => m[1]);

const modules = [];
const seen = new Map();
for (const dir of DIRS) {
  const files = (await readdir(join(DS, 'components', dir))).filter((f) => f.endsWith('.jsx')).sort();
  for (const file of files) {
    const rel = `components/${dir}/${file}`;
    const values = scan(await readFile(join(DS, rel), 'utf8'), NAMED);
    if (!values.length) continue;
    for (const name of values) {
      if (seen.has(name)) throw new Error(`Duplicate export "${name}": ${seen.get(name)} and ${rel}`);
      seen.set(name, rel);
    }
    const dts = rel.replace(/\.jsx$/, '.d.ts');
    let types = [];
    try { types = scan(await readFile(join(DS, dts), 'utf8'), TYPES); } catch { /* helper module, no contract */ }
    modules.push({ rel, dir, values, types, hasDts: types.length > 0 || rel !== dts });
  }
}

const head = (what) => `/* GENERATED by tools/build-barrel.mjs — do not edit by hand. Run \`npm run build:barrel\`.
   The public entry point of the Sentinel design system. Consumers import ${what} from here;
   _adherence.oxlintrc.json warns on any import that reaches into components/ directly. */\n`;

await writeFile(join(DS, 'index.js'),
  head('components') + DIRS.map((d) => {
    const rows = modules.filter((m) => m.dir === d);
    return rows.length ? `\n/* ${d} */\n` + rows.map((m) => `export { ${m.values.join(', ')} } from './${m.rel}';`).join('\n') : '';
  }).join('') + '\n');

await writeFile(join(DS, 'index.d.ts'),
  head('components and their prop types') + DIRS.map((d) => {
    const rows = modules.filter((m) => m.dir === d);
    return rows.length ? `\n/* ${d} */\n` + rows.map((m) => {
      const dts = './' + m.rel.replace(/\.jsx$/, '');
      const parts = [];
      if (m.types.length) parts.push(`export type { ${m.types.join(', ')} } from '${dts}';`);
      parts.push(`export { ${m.values.join(', ')} } from '${m.types.length ? dts : './' + m.rel}';`);
      return parts.join('\n');
    }).join('\n') : '';
  }).join('') + '\n');

console.log(`index.js + index.d.ts: ${modules.length} modules, ${seen.size} exports`);
