/* Regenerates .claude/skills/sentinel-craft/references/scale.md from tokens/*.css.

   The whole point of sentinel-craft is that its numbers are THIS system's, not a generic 4/8pt grid
   that would flag 11.5px type, a 42px row and 14px card padding as errors when all three are the
   product. So the scale is read off the token layer rather than typed into the skill, and the skill
   cannot drift from the system it audits. Run it whenever tokens change; CI checks it is current.

   Usage: npm run build:scale */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DS = join(ROOT, 'design-system');
const OUT = join(ROOT, '.claude/skills/sentinel-craft/references/scale.md');

const read = (f) => readFile(join(DS, 'tokens', f), 'utf8');
const [spacing, type, effects, colors] = await Promise.all(
  ['spacing.css', 'typography.css', 'effects.css', 'colors.css'].map(read));

/* Every --name:value in the file, in declaration order, with the comment that trails it. */
function decls(css) {
  const out = [];
  for (const m of css.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);(?:\s*\/\*([^*]*)\*\/)?/gi)) {
    out.push({ name: m[1], value: m[2].trim(), note: (m[3] || '').replace(/@kind\s+\w+/g, '').trim() });
  }
  return out;
}
const pick = (list, re) => list.filter((d) => re.test(d.name));
const px = (list) => [...new Set(list.map((d) => parseFloat(d.value)).filter((n) => !Number.isNaN(n)))].sort((a, b) => a - b);

const sp = decls(spacing), ty = decls(type), ef = decls(effects), co = decls(colors);

/* Which raw font sizes components still set by hand. Scanned, not asserted: the first draft of this
   file carried a sentence naming 11.5 and 10.5 as offenders, and it was wrong the day 11.5 became a
   published step. A note about the code has to be read off the code. */
const stepPx = new Set([...ty.filter((d) => /^--(text|display)-/.test(d.name)).map((d) => parseFloat(d.value))]);
const raw = new Map();
/* Skip dotfiles. Finder leaves a `.DS_Store` in any folder the owner looks at, and this read
   treated it as a component group and died with ENOTDIR — a build that a file manager can break. */
for (const dir of (await readdir(join(DS, 'components'))).filter((d) => !d.startsWith('.'))) {
  for (const file of (await readdir(join(DS, 'components', dir))).filter((f) => f.endsWith('.jsx'))) {
    const src = await readFile(join(DS, 'components', dir, file), 'utf8');
    for (const m of src.matchAll(/fontSize:\s*'?(-?\d+(?:\.\d+)?)'?/g)) {
      const v = parseFloat(m[1]);
      if (stepPx.has(v)) continue;
      if (!raw.has(v)) raw.set(v, new Set());
      raw.get(v).add(`components/${dir}/${file}`);
    }
  }
}

/* The three spacing tiers are the token file's own words, not a judgement made here: it labels
   4/8/12/16/20/24 the scale, 6 and 10 tolerated, and 2/3/5/13/14 exceptions to justify at use. */
const scaleSteps = px(pick(sp, /^--space-(4|8|12|16|20|24)$/));
const tolerated  = px(pick(sp, /^--space-(6|10)$/));
const exceptions = px(pick(sp, /^--space-(2|3|5|13|14)$/));
const radii      = pick(sp, /^--radius-/).filter((d) => d.name !== '--radius-full');
const heights    = pick(sp, /^--h-/);
const textSteps  = px(pick(ty, /^--text-/));
const displaySteps = px(pick(ty, /^--display-/));
const leadings   = px(pick(ty, /^--leading-/));
const roles      = pick(ty, /^--type-.*-font$/);
const durations  = pick(ef, /^--dur-/);
const presses    = pick(ef, /^--press-scale/);
const shadows    = pick(ef, /^--shadow-/);

const row = (d) => `| \`${d.name}\` | \`${d.value}\` | ${d.note.replace(/\s+/g, ' ').replace(/\|/g, '\\|') || ''} |`;
const table = (ds) => ['| Token | Value | What it is for |', '| --- | --- | --- |', ...ds.map(row)].join('\n');
const list = (ns) => ns.join(' · ');

const md = `<!-- GENERATED by tools/extract-scale.mjs from design-system/tokens/*.css. Do not edit.
     Run \`npm run build:scale\` after changing tokens; CI fails when this file is stale. -->

# Sentinel's actual scale

Every number an audit may hold this system to. Read from the token layer, so it cannot disagree with
the product. A value that is not here is a finding; a value that is here is **not** a finding, however
unusual it looks against a generic grid.

## Spacing — three tiers, not one

The token file states the tiers itself. Audit against these, never against a plain 4/8pt grid.

| Tier | Values | How to treat a use |
| --- | --- | --- |
| **The scale** | ${list(scaleSteps)} | Correct. Never flag. |
| **Tolerated in-betweens** | ${list(tolerated)} | Correct for chip and card internals. Never flag there; flag at layout level. |
| **Exceptions** | ${list(exceptions)} | Real, and each must be justified where it is used. Flag only when a new use adds no justification. |

Anything outside all three tiers is off-scale and is a finding.

Fixed dimensions that are not spacing and are never "rounded to the grid":

${table(heights)}

> \`--h-touch\` is the floor: **nothing operable is smaller than 44**. A visual box may be smaller —
> \`Pressable\` and \`Pill\` extend to 44 with a pseudo-element — but the target may not.

## Radius

${table(radii)}

Plus \`--radius-full\` (9999) for pills and chips. 16 and 20 are load-bearing: cards and the composer.

## Type

Raw steps: **${list(textSteps)}** · display **${list(displaySteps)}** · leadings **${list(leadings)}**.

A component asks for a **role**, never a number:

${table(roles)}

> A raw step is for something that genuinely needs one axis alone. A component reaching past both is
> a finding.
${raw.size
  ? `>\n> **Font sizes currently set by hand that are not steps** — each one is a finding:\n>\n` +
    [...raw.entries()].sort((a, b) => a[0] - b[0])
      .map(([v, files]) => `> - \`${v}\` — ${[...files].join(', ')}`).join('\n')
  : '>\n> No component currently sets a font size outside this ramp.'}

## Motion

${table([...durations, ...presses])}

Easing is one value, \`${(ef.find((d) => d.name === '--ease') || {}).value}\`, everywhere.

> **Press is ${(presses.find((d) => d.name === '--press-scale') || {}).value}, and ${(presses.find((d) => d.name === '--press-scale-icon') || {}).value} on 42px discs.** Any advice prescribing 0.96 is
> about a different product; it does not apply here.

## Shadows

${table(shadows)}

> Cards carry 5% ink at 1–2px, or a 1px ring — **never both heavy**. Depth is reserved for the
> composer, the floating disc, the drawer and the phone.

## Colour roles that carry meaning

${table(pick(co, /^--color-status-/))}

> The status family is **reserved**: never a series colour, and never used without a word beside it.

## Counts

${[
  ['spacing tokens', sp.filter((d) => d.name.startsWith('--space-')).length],
  ['radius tokens', radii.length + 1],
  ['type steps', textSteps.length + displaySteps.length],
  ['type roles', roles.length],
  ['durations', durations.length],
  ['shadow tokens', shadows.length],
].map(([k, v]) => `- ${v} ${k}`).join('\n')}
`;

await writeFile(OUT, md);
console.log(`scale.md: ${scaleSteps.length} scale steps, ${roles.length} type roles, ${radii.length + 1} radii, ${durations.length} durations`);
