/* GENERATED by tools/build-barrel.mjs — do not edit by hand. Run `npm run build:barrel`.
   The public entry point of the Sentinel design system. Consumers import components from here;
   _adherence.oxlintrc.json warns on any import that reaches into components/ directly. */

/* brand */
export { DotField } from './components/brand/DotField.jsx';
export { Mascot } from './components/brand/Mascot.jsx';
export { SplashScreen } from './components/brand/SplashScreen.jsx';
/* text */
export { Eyebrow } from './components/text/Eyebrow.jsx';
export { EyebrowDivider } from './components/text/EyebrowDivider.jsx';
export { Provenance } from './components/text/Provenance.jsx';
export { StandingDisclosure } from './components/text/StandingDisclosure.jsx';
/* icons */
export { MarkEquity, MarkDebt, MarkCommodity, MarkProperty, ASSET_MARKS, AssetMark } from './components/icons/AssetMark.jsx';
export { IconArrow } from './components/icons/IconArrow.jsx';
export { IconAttach } from './components/icons/IconAttach.jsx';
export { IconCheckCircle } from './components/icons/IconCheckCircle.jsx';
export { IconChevronRight } from './components/icons/IconChevronRight.jsx';
export { IconDownload } from './components/icons/IconDownload.jsx';
export { IconFile } from './components/icons/IconFile.jsx';
export { IconInfo } from './components/icons/IconInfo.jsx';
export { IconMenu } from './components/icons/IconMenu.jsx';
export { IconPlus } from './components/icons/IconPlus.jsx';
export { IconSparkle } from './components/icons/IconSparkle.jsx';
export { IconSpinner } from './components/icons/IconSpinner.jsx';
/* shell */
export { Dock } from './components/shell/Dock.jsx';
export { Drawer } from './components/shell/Drawer.jsx';
export { ExplorerSheet } from './components/shell/ExplorerSheet.jsx';
export { HomeIndicator } from './components/shell/HomeIndicator.jsx';
export { MOTION_CSS, REDUCED_MOTION_CSS, installReducedMotion, MotionGuard } from './components/shell/MotionGuard.jsx';
export { PathBar } from './components/shell/PathBar.jsx';
export { PhoneFrame } from './components/shell/PhoneFrame.jsx';
export { ScreenBackdrop } from './components/shell/ScreenBackdrop.jsx';
export { ScreenScaffold } from './components/shell/ScreenScaffold.jsx';
export { ScreenStack } from './components/shell/ScreenStack.jsx';
export { ScrollToBottomButton } from './components/shell/ScrollToBottomButton.jsx';
export { SectionStrip } from './components/shell/SectionStrip.jsx';
export { StatusSpacer } from './components/shell/StatusSpacer.jsx';
export { TopBar } from './components/shell/TopBar.jsx';
/* actions */
export { AnswerChip } from './components/actions/AnswerChip.jsx';
export { ChipRow } from './components/actions/ChipRow.jsx';
export { ClientChip } from './components/actions/ClientChip.jsx';
export { DarkButton } from './components/actions/DarkButton.jsx';
export { DownloadAction } from './components/actions/DownloadAction.jsx';
export { InfoDot } from './components/actions/InfoDot.jsx';
export { InlineActionRow } from './components/actions/InlineActionRow.jsx';
export { Pill } from './components/actions/Pill.jsx';
export { Pressable } from './components/actions/Pressable.jsx';
export { RangePills } from './components/actions/RangePills.jsx';
export { SegmentedRow } from './components/actions/SegmentedRow.jsx';
export { SuggestionRow } from './components/actions/SuggestionRow.jsx';
/* forms */
export { FileUpload } from './components/forms/FileUpload.jsx';
export { SearchField } from './components/forms/SearchField.jsx';
export { SelectionMark } from './components/forms/SelectionMark.jsx';
/* lists */
export { FollowUpRow } from './components/lists/FollowUpRow.jsx';
export { List } from './components/lists/List.jsx';
export { ListRow } from './components/lists/ListRow.jsx';
/* cards */
export { AllocationCard } from './components/cards/AllocationCard.jsx';
export { ArtifactCard } from './components/cards/ArtifactCard.jsx';
export { Badge } from './components/cards/Badge.jsx';
export { ConfirmSheet } from './components/cards/ConfirmSheet.jsx';
export { ConstraintCallout } from './components/cards/ConstraintCallout.jsx';
export { DataTable } from './components/cards/DataTable.jsx';
export { DataTableCard } from './components/cards/DataTableCard.jsx';
export { DisclosureBlock } from './components/cards/DisclosureBlock.jsx';
export { ExplainerSheet } from './components/cards/ExplainerSheet.jsx';
export { FilterSheet } from './components/cards/FilterSheet.jsx';
export { FundCard } from './components/cards/FundCard.jsx';
export { useCountUp, HeroNumberCard } from './components/cards/HeroNumberCard.jsx';
export { InfoCard } from './components/cards/InfoCard.jsx';
export { IntentTile, IntentGrid } from './components/cards/IntentTile.jsx';
export { MoveCard } from './components/cards/MoveCard.jsx';
export { RejectCallout } from './components/cards/RejectCallout.jsx';
export { ResultCard, ResultActions, ResultPrimary } from './components/cards/ResultCard.jsx';
export { ShortlistCard } from './components/cards/ShortlistCard.jsx';
export { Surface } from './components/cards/Surface.jsx';
/* chat */
export { AttachmentTurn } from './components/chat/AttachmentTurn.jsx';
export { DetourBanner } from './components/chat/DetourBanner.jsx';
export { GreetingDivider } from './components/chat/GreetingDivider.jsx';
export { MessageActions } from './components/chat/MessageActions.jsx';
export { ParseNote } from './components/chat/ParseNote.jsx';
export { ProgressTrace } from './components/chat/ProgressTrace.jsx';
export { QAPair } from './components/chat/QAPair.jsx';
export { RefusalTurn } from './components/chat/RefusalTurn.jsx';
export { ResponseFeedback } from './components/chat/ResponseFeedback.jsx';
export { SentinelBlock } from './components/chat/SentinelBlock.jsx';
export { SentinelText } from './components/chat/SentinelText.jsx';
export { SentinelThinking } from './components/chat/SentinelThinking.jsx';
export { SentinelTurn } from './components/chat/SentinelTurn.jsx';
export { StepBlock, StepStack } from './components/chat/StepBlock.jsx';
export { StepTrace } from './components/chat/StepTrace.jsx';
export { UserBubble } from './components/chat/UserBubble.jsx';
export { UserTurn } from './components/chat/UserTurn.jsx';
export { VersionRow } from './components/chat/VersionRow.jsx';
/* composer */
export { Composer } from './components/composer/Composer.jsx';
export { formatINR, MoneyComposer } from './components/composer/MoneyComposer.jsx';
export { StepComposer } from './components/composer/StepComposer.jsx';
/* data */
export { AttributionChart } from './components/data/AttributionChart.jsx';
export { ChartBar } from './components/data/ChartBar.jsx';
export { ChartDonut } from './components/data/ChartDonut.jsx';
export { ChartLegend } from './components/data/ChartLegend.jsx';
export { ChartLine, ChartLineMultiples } from './components/data/ChartLine.jsx';
export { ChartReadout } from './components/data/ChartReadout.jsx';
export { ChartShare } from './components/data/ChartShare.jsx';
export { ChartSpark } from './components/data/ChartSpark.jsx';
export { ChartTooltip } from './components/data/ChartTooltip.jsx';
export { CompareTable } from './components/data/CompareTable.jsx';
export { ConcentrationBar } from './components/data/ConcentrationBar.jsx';
export { DrawnCheck } from './components/data/DrawnCheck.jsx';
export { Dumbbell } from './components/data/Dumbbell.jsx';
export { FigureRow } from './components/data/FigureRow.jsx';
export { MetricRow, MetricList } from './components/data/MetricRow.jsx';
export { OverlapView } from './components/data/OverlapView.jsx';
export { PeerLine } from './components/data/PeerLine.jsx';
export { ProgressRail } from './components/data/ProgressRail.jsx';
export { StatTile, Sparkline } from './components/data/StatTile.jsx';
export { hasD3, niceDomain, ticks, linear, band, linePath, areaPath, CHART_RAMP, CHART_EDGE, edgeColor, toneColor, markColor, SEGMENT_GAP, trackInset, PLOT, AXIS_BAND, tabular } from './components/data/chartMath.jsx';
